### PR TITLE
everybody wants to be

### PR DESCRIPTION
**Pull request by Piplup7575**

### CODE REVIEW

**Comment by Piplup7575** [comment]
my enemy

**Comment by 3kh0** [comment]
image

just make it the readme.md file lol

**Comment by Piplup7575** [comment]
i will lol
let me finish i dont want to overright what you have right now

**Comment by 3kh0** [comment]
ok lol

image

**Comment by Piplup7575** [comment]
all good

**Review by md4r2 — APPROVED** [review]

**Review by 3kh0 — APPROVED** [review]

**Review by Aka-unblock — COMMENTED** [review]
Sick

**Pull request merged**
