### PR TITLE
GuardianTabCrash Tab Limit Abuse

### PR DESCRIPTION
**Pull request by py660**

### CODE REVIEW

**Comment by py660** [comment]
also my formatting might be a bit off, i think i might have forgotten to put the back to top link 😢

**Comment by py660** [comment]
Hewo

**Review by 3kh0 — CHANGES_REQUESTED** [review]
Put in the back to top link

**Comment by py660** [comment]
Oops i pressed the rerequest button too soon :(

**Review by py660 — COMMENTED** [review]
just added the back to top link

**Comment by py660** [comment]
ugh that didn't work

**Review by 3kh0 — APPROVED** [review]

**Comment by py660** [comment]
👏 👏 👏 👏

**Pull request merged**
