### PR TITLE
Add rigtools

### PR DESCRIPTION
**Pull request by HelloIloveGimkit2**

### CODE REVIEW

**Comment by Inglan** [comment]
Looks like the codesandbox is down. Provide instructions on how to run your own server just in case anyone wants to do it (like me)

**Review by 3kh0 — APPROVED** [review]
very cool

image

**Comment by HelloIloveGimkit2** [comment]
> Looks like the codesandbox is down. Provide instructions on how to run your own server just in case anyone wants to do it (like me)

uh there's the GitHub to check it out and self host Also if you want I would recommend the new ui by sincereham cuz it's better and just has a codesandbox you can fork

**Comment by HelloIloveGimkit2** [comment]
And just to note sometimes it does say that just reconnect or refresh and it should start working

**Comment by 3kh0** [comment]
@HelloIloveGimkit2 I changed the URL to one hosted by kxtz in 5dbb103ad4fd79327dbbf6182e2b376b6425b71f

**Comment by HelloIloveGimkit2** [comment]
yeah I saw

**Pull request merged**
